version: "3.9"

services:
  backend:
    build: ./breezy-backend
    ports:
      - "5000:5000"
    volumes:
      - ./breezy-backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./breezy-frontend
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./breezy-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
