services:
  auth:
    build: ./breezy-back-auth
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - auth-mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  auth-mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - auth-mongo-data:/data/db
    networks:
      - app-network

  public:
    build: ./breezy-back-public
    ports:
      - "3002:3000"
    networks:
      - app-network
    depends_on:
      - public-mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  public-mongo:
    image: mongo:6.0
    container_name: public-mongo
    ports:
      - "27018:27017"
    volumes:
      - public-mongo-data:/data/db
    networks:
      - app-network

  private:
    build: ./breezy-back-private
    ports:
      - "3003:3000"
    networks:
      - app-network
    depends_on:
      - private-mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  private-mongo:
    image: mongo:6.0
    container_name: private-mongo
    ports:
      - "27019:27017"
    volumes:
      - private-mongo-data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      auth:
        condition: service_healthy
      public:
        condition: service_healthy
      private:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./breezy-frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./breezy-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth-mongo-data:
  public-mongo-data:
  private-mongo-data:
